/**
 * Builds the emoji picker's dataset from emojibase.
 *
 * ## Why generated and not hand-written
 *
 * The list used to be typed out by hand — about 130 characters with keywords somebody had
 * thought of. That has two failure modes and this repository hit both. It is incomplete in
 * ways nobody can predict (the emoji you want is the one that is missing), and it silently
 * includes characters the platform cannot draw: 🫡 🫠 🫶 were in the hand-written list and
 * rendered as empty boxes on Windows 10, because Segoe UI Emoji stops at Emoji 12.0.
 *
 * emojibase is the CLDR data — every emoji, with the annotations people actually search by
 * ("thanks" for 🙏) and, critically, a `version` field saying which Emoji release
 * introduced each one.
 *
 * ## What is filtered out, and why each one
 *
 * - **Above `MAX_EMOJI_VERSION`.** The rendering font is bundled (Noto Color Emoji), so
 *   the glyph will draw — but the picker is also used to REACT, and a reaction is stored
 *   as text and re-rendered anywhere the recipient reads it, including a phone that has
 *   not been updated in three years. Newer than this and it is a box on somebody's screen.
 * - **Skin-tone variants.** Five copies of every hand multiplies the set by four for no
 *   information gain in a workplace picker, and the base emoji is what people type.
 * - **Flags.** 270 of them, they are never the reaction anybody wants, and a national flag
 *   is the one emoji category with a way of causing an incident.
 *
 * Run: `node scripts/generate-emoji.mjs` from apps/employee-web. Committed output, so a
 * build needs no network and a reviewer can see exactly what changed.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const emoji = require('emojibase-data/en/compact.json');
const groups = require('emojibase-data/meta/groups.json');

/** Emoji 14.0 is 2021, and is drawn by every phone and desktop still in support. */
const MAX_EMOJI_VERSION = 14;

/**
 * The picker's tabs, in the order they appear.
 *
 * CLDR's own groups, with two joined: "people-body" alone is mostly hands and gestures,
 * which belong with the faces people reach for them alongside. Flags are excluded above,
 * so that group has no tab.
 */
const TABS = [
  { id: 'smileys', label: 'Smileys & people', groups: [0, 1], tab: '🙂' },
  { id: 'nature', label: 'Animals & nature', groups: [3], tab: '🌿' },
  { id: 'food', label: 'Food & drink', groups: [4], tab: '🍜' },
  { id: 'activity', label: 'Activity & travel', groups: [5, 6], tab: '⚽' },
  { id: 'objects', label: 'Objects', groups: [7], tab: '💡' },
  { id: 'symbols', label: 'Symbols', groups: [8], tab: '✅' },
];

const groupOf = new Map(Object.entries(groups.groups).map(([id, key]) => [Number(id), key]));
void groupOf;

const seen = new Set();
const byTab = new Map(TABS.map((t) => [t.id, []]));

for (const entry of emoji) {
  if (entry.version > MAX_EMOJI_VERSION) continue;
  if (entry.group === undefined) continue;

  const tab = TABS.find((t) => t.groups.includes(entry.group));
  if (tab === undefined) continue;

  // `unicode` on the compact record is the base, tone-free form.
  const glyph = entry.unicode;
  if (seen.has(glyph)) continue;
  seen.add(glyph);

  /*
     The label plus its annotations, deduplicated and lower-cased — this is what search
     matches on. The label alone is not enough: nobody searches 🙏 by "folded hands".
  */
  const words = [entry.label, ...(entry.tags ?? [])]
    .join(' ')
    .toLowerCase()
    .replace(/[^a-z0-9 ]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean);

  byTab.get(tab.id).push([glyph, [...new Set(words)].join(' ')]);
}

const HERE = dirname(fileURLToPath(import.meta.url));
const target = resolve(HERE, '..', 'src', 'components', 'emoji-data.generated.ts');

const body = TABS.map((tab) => {
  const rows = byTab
    .get(tab.id)
    .map(([glyph, words]) => `    ['${glyph}', ${JSON.stringify(words)}],`)
    .join('\n');
  return `  {
    id: '${tab.id}',
    tab: '${tab.tab}',
    label: ${JSON.stringify(tab.label)},
    emoji: [
${rows}
    ],
  },`;
}).join('\n');

const total = [...byTab.values()].reduce((n, list) => n + list.length, 0);

writeFileSync(
  target,
  `/* GENERATED by scripts/generate-emoji.mjs — do not edit by hand.
 *
 * ${total} emoji from emojibase (CLDR), Emoji ${MAX_EMOJI_VERSION} and below, base skin
 * tone only, flags excluded. Regenerate with \`node scripts/generate-emoji.mjs\`.
 *
 * See the generator for why each filter is there.
 */
export interface EmojiGroup {
  readonly id: string;
  /** The category button's glyph. */
  readonly tab: string;
  readonly label: string;
  /** \`[glyph, search keywords]\`. */
  readonly emoji: readonly (readonly [string, string])[];
}

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
${body}
];
`,
  'utf8',
);

console.log(`wrote ${total} emoji across ${TABS.length} groups -> ${target}`);
