global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: starlink-api
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: starlink-realtime
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3100']
  - job_name: starlink-workers
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3200']
